### ISSUE TITLE
Airline font is broken on Mac

### ISSUE THREAD

**Issue by darthdeus** [belluzj/fantasque-sans#54]
Similar as in #22, I'm having trouble with the airline glyphs on Mac.

![image](https://cloud.githubusercontent.com/assets/123374/10967946/77377940-83be-11e5-9979-d9857b797cf2.png)

but I'm having no trouble on Linux. I've tried both the .ttf and .otf versions.

**Comment by belluzj** [comment]
I don't have a Mac to perform tests, so this will wait until someone else figures it out, sorry.

**Comment by AnotherWorkingNerd** [comment]
I know this issue is almost a year old. but I just found your font and like it a lot. I've been using Droid but yours has more character (DOH! ). Anyway I'm using a MacBook Pro with OS X Yosemite.  I was playing with Airline and your font and I discovered 2 things. 1. your font seem to perform better than the "Droid Sans Mono Slashed for Powerline Regular" that I had been using when using MacVim 8.0(114) but seem to have some character issues when using vim 7.4 through iTerm2

I can provide screen shots if needed.
Greg.

**Comment by AnotherWorkingNerd** [comment]
DOH! Ignore what I said about " seem to have some character issues when using vim 7.4 through iTerm2". I forgot to set iTerm2 to use your font (1.71) and when I did all worked fine. I'm new to airline and just have the basic config. if I come across anything odd, font wise I'll let you know.

**Comment by AnotherWorkingNerd** [comment]
I got the git stuff working with airline and I tried a couple different repos that do and don't have branches and all seemed to work well. using your font v1.7.1 with MacVim 8.0 and vim 7.4 with no problems.

![image](https://cloud.githubusercontent.com/assets/18605879/20021615/ddbf6142-a293-11e6-9748-feaff950b119.png)
