### ISSUE TITLE
● symbol too large

### ISSUE THREAD

**Issue by tpict** [belluzj/fantasque-sans#78]
![screenshot from 2017-05-11 14-02-03](https://cloud.githubusercontent.com/assets/12588098/25950327/7b4eacf4-3652-11e7-88b4-c20aaff47cad.png)
On Ubuntu 16.04 with [this](https://github.com/belluzj/fantasque-sans/releases/download/v1.7.1/FantasqueSansMono.zip) build of the font, the ● symbol is too large - it either overflows into the next character or gets cropped off at the side

edit: it looks fine on OS X though

**Comment by belluzj** [comment]
It's too large because it's not included in this font, so it must be fetched from another one of your system's font.

I will keep this issue open to remind me to add this symbol someday. In the meantime, maybe you can switch to using the • glyph (bullet), which is provided in this font (although it is smaller than your circle).

**Comment by tpict** [comment]
Thanks!
