### ISSUE TITLE
Precompiled Release For Non-Monospaced Version

### ISSUE THREAD

**Issue by JShorthouse** [belluzj/fantasque-sans#90]
I've just installed this font and I really love it, and now i'd also like a non-monospaced variant to use as my i3wm font.

If I'm not mistaken there is also a non-monospaced variant in this repository, is there any reason why this isn't included in the releases?

**Comment by belluzj** [comment]
It's not included because I don't work on the proportional font, mostly because I don't think it has the potential to be useful, and its font qualities are currently low (small character set, only one weight rather on the light side, bad spacing/kerning...) For example I think it would make a bad UI font, because its shapes and spacing are not screen-friendly. Also it feels (to me) even goofier than the monospace :)

I'll let you judge for yourself: [FantasqueSans.zip](https://github.com/belluzj/fantasque-sans/files/1770300/FantasqueSans.zip)

**Comment by chrisfcarroll** [comment]
Oh most beneficient Belluzj! It is a marvellous font. Thankyou.
